import {
  Location,
  RiskAssessment,
  HistoricalLandslide,
  Alert,
  Notification,
  LocationDetail,
  DataSource,
} from '../types';

export const MOCK_LOCATIONS: Location[] = [
  {
    id: 'aizawl',
    name: 'Aizawl Catchment',
    district: 'Aizawl',
    state: 'Mizoram',
    country: 'India',
    coordinates: { lat: 23.7307, lon: 92.7173 },
    population: 293000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-aizawl',
      locationId: 'aizawl',
      locationName: 'Aizawl Catchment',
      district: 'Aizawl',
      state: 'Mizoram',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 78.4,
      impactScore: 72.1,
      finalScore: 75.8,
      riskLevel: 'CRITICAL',
      priorityLevel: 'P1',
      trend: 'RISING',
      trendPct: 14.2,
      componentScores: { rainfall: 0.78, slope: 0.85, soil: 0.72, landCover: 0.65, drainage: 0.74, historical: 0.81 },
      inputs: {
        rainfall_current_mmph: 18.4,
        rainfall_24h_mm: 86.5,
        rainfall_72h_mm: 142.0,
        forecast_6h_mm: 24.5,
        forecast_24h_mm: 68.0,
        slope_deg: 38.4,
        soilSusceptibility: 0.84,
        landCoverSusceptibility: 0.72,
        drainageProximityKm: 0.15,
        historicalEventsNearby: 6,
      },
      explanation: [
        { factor: 'Rainfall Saturation', value: '86.5 mm (24h)', contribution: 38, label: 'HIGH' },
        { factor: 'Escarpment Slope', value: '38.4°', contribution: 32, label: 'HIGH' },
        { factor: 'Colluvium Overburden', value: 'High Pore Pressure', contribution: 30, label: 'HIGH' },
      ],
      recommendations: [
        'Immediate dispatch of NDRF 1st Bn inspection team',
        'Activate evacuation protocol along Ramhlun South ridge corridor',
      ],
      dataQuality: { rainfall: 'GOOD', dem: 'GOOD', soil: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'shillong',
    name: 'Shillong Peak & Valley',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    country: 'India',
    coordinates: { lat: 25.5788, lon: 91.8933 },
    population: 143000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-shillong',
      locationId: 'shillong',
      locationName: 'Shillong Peak & Valley',
      district: 'East Khasi Hills',
      state: 'Meghalaya',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 68.2,
      impactScore: 65.4,
      finalScore: 67.1,
      riskLevel: 'HIGH',
      priorityLevel: 'P2',
      trend: 'RISING',
      trendPct: 8.5,
      componentScores: { rainfall: 0.69, slope: 0.72, soil: 0.64, landCover: 0.58, drainage: 0.62, historical: 0.78 },
      inputs: {
        rainfall_current_mmph: 12.2,
        rainfall_24h_mm: 64.2,
        rainfall_72h_mm: 118.4,
        forecast_6h_mm: 18.0,
        forecast_24h_mm: 52.0,
        slope_deg: 32.1,
        soilSusceptibility: 0.76,
        landCoverSusceptibility: 0.62,
        drainageProximityKm: 0.22,
        historicalEventsNearby: 4,
      },
      explanation: [
        { factor: 'Soil Saturation Index', value: '0.76 High', contribution: 40, label: 'HIGH' },
        { factor: 'NH-6 Highway Exposure', value: 'Arterial Cut', contribution: 35, label: 'HIGH' },
      ],
      recommendations: ['Clear culverts along NH-6 highway', 'Deploy traffic advisory'],
      dataQuality: { rainfall: 'GOOD', dem: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'gangtok',
    name: 'Gangtok Urban Ridge',
    district: 'East Sikkim',
    state: 'Sikkim',
    country: 'India',
    coordinates: { lat: 27.3389, lon: 88.6065 },
    population: 100000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-gangtok',
      locationId: 'gangtok',
      locationName: 'Gangtok Urban Ridge',
      district: 'East Sikkim',
      state: 'Sikkim',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 71.5,
      impactScore: 68.0,
      finalScore: 70.1,
      riskLevel: 'CRITICAL',
      priorityLevel: 'P1',
      trend: 'RISING',
      trendPct: 11.2,
      componentScores: { rainfall: 0.74, slope: 0.82, soil: 0.68, landCover: 0.61, drainage: 0.70, historical: 0.76 },
      inputs: {
        rainfall_current_mmph: 15.6,
        rainfall_24h_mm: 72.8,
        rainfall_72h_mm: 135.0,
        forecast_6h_mm: 22.0,
        forecast_24h_mm: 61.0,
        slope_deg: 36.8,
        soilSusceptibility: 0.81,
        landCoverSusceptibility: 0.68,
        drainageProximityKm: 0.18,
        historicalEventsNearby: 5,
      },
      explanation: [
        { factor: 'Sub-surface Creep', value: 'Active Displacement', contribution: 42, label: 'HIGH' },
        { factor: 'Deorali Slope Gradient', value: '36.8°', contribution: 33, label: 'HIGH' },
      ],
      recommendations: ['Triage civil protection at Paljor Stadium shelter', 'Issue CAP alert'],
      dataQuality: { rainfall: 'GOOD', dem: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'kohima',
    name: 'Kohima Municipal Ridge',
    district: 'Kohima',
    state: 'Nagaland',
    country: 'India',
    coordinates: { lat: 25.6751, lon: 94.1086 },
    population: 99000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-kohima',
      locationId: 'kohima',
      locationName: 'Kohima Municipal Ridge',
      district: 'Kohima',
      state: 'Nagaland',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 63.4,
      impactScore: 61.2,
      finalScore: 62.5,
      riskLevel: 'HIGH',
      priorityLevel: 'P2',
      trend: 'STABLE',
      trendPct: 1.2,
      componentScores: { rainfall: 0.58, slope: 0.75, soil: 0.66, landCover: 0.54, drainage: 0.60, historical: 0.68 },
      inputs: {
        rainfall_current_mmph: 8.4,
        rainfall_24h_mm: 48.0,
        rainfall_72h_mm: 92.5,
        forecast_6h_mm: 12.0,
        forecast_24h_mm: 36.0,
        slope_deg: 34.2,
        soilSusceptibility: 0.71,
        landCoverSusceptibility: 0.59,
        drainageProximityKm: 0.28,
        historicalEventsNearby: 3,
      },
      explanation: [{ factor: 'Weathered Shale Strata', value: 'Disang Group', contribution: 45, label: 'HIGH' }],
      recommendations: ['Monitor NH-29 bypass road section'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'haflong',
    name: 'Haflong Hill Station',
    district: 'Dima Hasao',
    state: 'Assam',
    country: 'India',
    coordinates: { lat: 25.1764, lon: 93.0182 },
    population: 43000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-haflong',
      locationId: 'haflong',
      locationName: 'Haflong Hill Station',
      district: 'Dima Hasao',
      state: 'Assam',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 58.6,
      impactScore: 54.2,
      finalScore: 56.8,
      riskLevel: 'HIGH',
      priorityLevel: 'P2',
      trend: 'RISING',
      trendPct: 6.4,
      componentScores: { rainfall: 0.62, slope: 0.68, soil: 0.59, landCover: 0.51, drainage: 0.54, historical: 0.65 },
      inputs: {
        rainfall_current_mmph: 10.1,
        rainfall_24h_mm: 52.4,
        rainfall_72h_mm: 98.0,
        forecast_6h_mm: 14.0,
        forecast_24h_mm: 42.0,
        slope_deg: 31.5,
        soilSusceptibility: 0.68,
        landCoverSusceptibility: 0.55,
        drainageProximityKm: 0.35,
        historicalEventsNearby: 4,
      },
      explanation: [{ factor: 'Railway Cutting Slope', value: 'Colluvium Failure', contribution: 44, label: 'HIGH' }],
      recommendations: ['Inspect Lumding-Badarpur rail link drainage'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'durtlang',
    name: 'Durtlang North Ridge',
    district: 'Aizawl',
    state: 'Mizoram',
    country: 'India',
    coordinates: { lat: 23.7712, lon: 92.7305 },
    population: 18500,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-durtlang',
      locationId: 'durtlang',
      locationName: 'Durtlang North Ridge',
      district: 'Aizawl',
      state: 'Mizoram',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 66.8,
      impactScore: 59.4,
      finalScore: 63.8,
      riskLevel: 'HIGH',
      priorityLevel: 'P2',
      trend: 'RISING',
      trendPct: 9.8,
      componentScores: { rainfall: 0.65, slope: 0.84, soil: 0.62, landCover: 0.52, drainage: 0.59, historical: 0.68 },
      inputs: {
        rainfall_current_mmph: 14.1,
        rainfall_24h_mm: 68.5,
        rainfall_72h_mm: 124.0,
        forecast_6h_mm: 20.0,
        forecast_24h_mm: 55.0,
        slope_deg: 37.5,
        soilSusceptibility: 0.77,
        landCoverSusceptibility: 0.60,
        drainageProximityKm: 0.20,
        historicalEventsNearby: 4,
      },
      explanation: [{ factor: 'Cliff Joint Hydrostatic Pressure', value: 'Elevated', contribution: 55, label: 'HIGH' }],
      recommendations: ['Maintain safety netting along Leitan escarpment'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'mawsynram',
    name: 'Mawsynram Precipitation Belt',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    country: 'India',
    coordinates: { lat: 25.2974, lon: 91.5828 },
    population: 18000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-mawsynram',
      locationId: 'mawsynram',
      locationName: 'Mawsynram Precipitation Belt',
      district: 'East Khasi Hills',
      state: 'Meghalaya',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 52.4,
      impactScore: 42.1,
      finalScore: 48.2,
      riskLevel: 'MODERATE',
      priorityLevel: 'P3',
      trend: 'FALLING',
      trendPct: -3.8,
      componentScores: { rainfall: 0.82, slope: 0.58, soil: 0.44, landCover: 0.38, drainage: 0.45, historical: 0.41 },
      inputs: {
        rainfall_current_mmph: 22.4,
        rainfall_24h_mm: 112.0,
        rainfall_72h_mm: 240.0,
        forecast_6h_mm: 28.0,
        forecast_24h_mm: 85.0,
        slope_deg: 28.6,
        soilSusceptibility: 0.89,
        landCoverSusceptibility: 0.40,
        drainageProximityKm: 0.12,
        historicalEventsNearby: 2,
      },
      explanation: [{ factor: 'Heavy Pluvial Runoff', value: '112.0 mm / 24h', contribution: 58, label: 'HIGH' }],
      recommendations: ['Routine monitoring; karst drainage functioning normally'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'jowai',
    name: 'Jowai District Headquarter',
    district: 'West Jaintia Hills',
    state: 'Meghalaya',
    country: 'India',
    coordinates: { lat: 25.4526, lon: 92.2038 },
    population: 28400,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-jowai',
      locationId: 'jowai',
      locationName: 'Jowai District Headquarter',
      district: 'West Jaintia Hills',
      state: 'Meghalaya',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 44.2,
      impactScore: 41.0,
      finalScore: 42.8,
      riskLevel: 'MODERATE',
      priorityLevel: 'P3',
      trend: 'STABLE',
      trendPct: 0.4,
      componentScores: { rainfall: 0.48, slope: 0.55, soil: 0.42, landCover: 0.39, drainage: 0.41, historical: 0.52 },
      inputs: {
        rainfall_current_mmph: 6.2,
        rainfall_24h_mm: 38.0,
        rainfall_72h_mm: 74.5,
        forecast_6h_mm: 8.0,
        forecast_24h_mm: 25.0,
        slope_deg: 29.8,
        soilSusceptibility: 0.62,
        landCoverSusceptibility: 0.48,
        drainageProximityKm: 0.45,
        historicalEventsNearby: 2,
      },
      explanation: [{ factor: 'Myntdu River Valley Runoff', value: 'Normal', contribution: 48, label: 'MODERATE' }],
      recommendations: ['Routine surveillance'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'namchi',
    name: 'Namchi Hill Ridge',
    district: 'South Sikkim',
    state: 'Sikkim',
    country: 'India',
    coordinates: { lat: 27.1667, lon: 88.35 },
    population: 35000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-namchi',
      locationId: 'namchi',
      locationName: 'Namchi Hill Ridge',
      district: 'South Sikkim',
      state: 'Sikkim',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 49.8,
      impactScore: 46.5,
      finalScore: 48.4,
      riskLevel: 'MODERATE',
      priorityLevel: 'P3',
      trend: 'RISING',
      trendPct: 4.1,
      componentScores: { rainfall: 0.45, slope: 0.70, soil: 0.52, landCover: 0.41, drainage: 0.48, historical: 0.55 },
      inputs: {
        rainfall_current_mmph: 7.8,
        rainfall_24h_mm: 41.2,
        rainfall_72h_mm: 79.0,
        forecast_6h_mm: 10.0,
        forecast_24h_mm: 32.0,
        slope_deg: 33.4,
        soilSusceptibility: 0.64,
        landCoverSusceptibility: 0.50,
        drainageProximityKm: 0.38,
        historicalEventsNearby: 2,
      },
      explanation: [{ factor: 'Terrace Gradient', value: '33.4°', contribution: 45, label: 'MODERATE' }],
      recommendations: ['Routine surveillance'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'senapati',
    name: 'Senapati Hill Slopes',
    district: 'Senapati',
    state: 'Manipur',
    country: 'India',
    coordinates: { lat: 25.2667, lon: 94.0167 },
    population: 32000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-senapati',
      locationId: 'senapati',
      locationName: 'Senapati Hill Slopes',
      district: 'Senapati',
      state: 'Manipur',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 46.0,
      impactScore: 43.5,
      finalScore: 45.0,
      riskLevel: 'MODERATE',
      priorityLevel: 'P3',
      trend: 'STABLE',
      trendPct: 1.1,
      componentScores: { rainfall: 0.44, slope: 0.62, soil: 0.49, landCover: 0.40, drainage: 0.43, historical: 0.50 },
      inputs: {
        rainfall_current_mmph: 5.4,
        rainfall_24h_mm: 34.0,
        rainfall_72h_mm: 68.0,
        forecast_6h_mm: 7.0,
        forecast_24h_mm: 22.0,
        slope_deg: 30.2,
        soilSusceptibility: 0.59,
        landCoverSusceptibility: 0.45,
        drainageProximityKm: 0.50,
        historicalEventsNearby: 2,
      },
      explanation: [{ factor: 'NH-2 Highway Cutting Incline', value: '30.2°', contribution: 50, label: 'MODERATE' }],
      recommendations: ['Routine surveillance'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'ukhrul',
    name: 'Ukhrul Mountain Sector',
    district: 'Ukhrul',
    state: 'Manipur',
    country: 'India',
    coordinates: { lat: 25.1167, lon: 94.3667 },
    population: 26000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-ukhrul',
      locationId: 'ukhrul',
      locationName: 'Ukhrul Mountain Sector',
      district: 'Ukhrul',
      state: 'Manipur',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 47.5,
      impactScore: 41.2,
      finalScore: 44.8,
      riskLevel: 'MODERATE',
      priorityLevel: 'P3',
      trend: 'FALLING',
      trendPct: -2.4,
      componentScores: { rainfall: 0.38, slope: 0.74, soil: 0.48, landCover: 0.36, drainage: 0.40, historical: 0.46 },
      inputs: {
        rainfall_current_mmph: 4.8,
        rainfall_24h_mm: 29.5,
        rainfall_72h_mm: 61.0,
        forecast_6h_mm: 6.0,
        forecast_24h_mm: 18.0,
        slope_deg: 35.1,
        soilSusceptibility: 0.55,
        landCoverSusceptibility: 0.42,
        drainageProximityKm: 0.60,
        historicalEventsNearby: 1,
      },
      explanation: [{ factor: 'High Elevation Escarpment', value: '1662m', contribution: 52, label: 'MODERATE' }],
      recommendations: ['Routine surveillance'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'champhai',
    name: 'Champhai Border Ridge',
    district: 'Champhai',
    state: 'Mizoram',
    country: 'India',
    coordinates: { lat: 23.4757, lon: 93.3297 },
    population: 33000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-champhai',
      locationId: 'champhai',
      locationName: 'Champhai Border Ridge',
      district: 'Champhai',
      state: 'Mizoram',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 41.0,
      impactScore: 36.5,
      finalScore: 39.2,
      riskLevel: 'MODERATE',
      priorityLevel: 'P3',
      trend: 'STABLE',
      trendPct: 0.2,
      componentScores: { rainfall: 0.35, slope: 0.60, soil: 0.42, landCover: 0.34, drainage: 0.38, historical: 0.42 },
      inputs: {
        rainfall_current_mmph: 3.2,
        rainfall_24h_mm: 22.0,
        rainfall_72h_mm: 48.0,
        forecast_6h_mm: 5.0,
        forecast_24h_mm: 15.0,
        slope_deg: 31.0,
        soilSusceptibility: 0.51,
        landCoverSusceptibility: 0.38,
        drainageProximityKm: 0.70,
        historicalEventsNearby: 1,
      },
      explanation: [{ factor: 'Colluvial Mantle Stability', value: 'Adequate', contribution: 45, label: 'LOW' }],
      recommendations: ['Routine surveillance'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'wokha',
    name: 'Wokha Hill Range',
    district: 'Wokha',
    state: 'Nagaland',
    country: 'India',
    coordinates: { lat: 26.0984, lon: 94.2616 },
    population: 35000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-wokha',
      locationId: 'wokha',
      locationName: 'Wokha Hill Range',
      district: 'Wokha',
      state: 'Nagaland',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 36.5,
      impactScore: 32.0,
      finalScore: 34.6,
      riskLevel: 'MODERATE',
      priorityLevel: 'P3',
      trend: 'STABLE',
      trendPct: 0.0,
      componentScores: { rainfall: 0.32, slope: 0.54, soil: 0.38, landCover: 0.31, drainage: 0.34, historical: 0.39 },
      inputs: {
        rainfall_current_mmph: 2.5,
        rainfall_24h_mm: 18.0,
        rainfall_72h_mm: 42.0,
        forecast_6h_mm: 4.0,
        forecast_24h_mm: 12.0,
        slope_deg: 29.5,
        soilSusceptibility: 0.48,
        landCoverSusceptibility: 0.35,
        drainageProximityKm: 0.80,
        historicalEventsNearby: 1,
      },
      explanation: [{ factor: 'Barail Sandstone Bedrock', value: 'Stable', contribution: 40, label: 'LOW' }],
      recommendations: ['Routine surveillance'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'viswema',
    name: 'Viswema Foothills Sector',
    district: 'Kohima',
    state: 'Nagaland',
    country: 'India',
    coordinates: { lat: 25.5500, lon: 94.1500 },
    population: 8500,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-viswema',
      locationId: 'viswema',
      locationName: 'Viswema Foothills Sector',
      district: 'Kohima',
      state: 'Nagaland',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 28.0,
      impactScore: 22.0,
      finalScore: 25.5,
      riskLevel: 'LOW',
      priorityLevel: 'P4',
      trend: 'FALLING',
      trendPct: -4.5,
      componentScores: { rainfall: 0.18, slope: 0.58, soil: 0.28, landCover: 0.22, drainage: 0.25, historical: 0.28 },
      inputs: {
        rainfall_current_mmph: 0.8,
        rainfall_24h_mm: 9.5,
        rainfall_72h_mm: 24.0,
        forecast_6h_mm: 2.0,
        forecast_24h_mm: 6.0,
        slope_deg: 32.0,
        soilSusceptibility: 0.38,
        landCoverSusceptibility: 0.25,
        drainageProximityKm: 1.2,
        historicalEventsNearby: 0,
      },
      explanation: [{ factor: 'Stable Soil Matrix', value: 'Normal', contribution: 60, label: 'LOW' }],
      recommendations: ['Normal routine operations'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'maibang',
    name: 'Maibang Mahur Basin',
    district: 'Dima Hasao',
    state: 'Assam',
    country: 'India',
    coordinates: { lat: 25.2917, lon: 93.1611 },
    population: 12000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-maibang',
      locationId: 'maibang',
      locationName: 'Maibang Mahur Basin',
      district: 'Dima Hasao',
      state: 'Assam',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 24.5,
      impactScore: 19.5,
      finalScore: 22.4,
      riskLevel: 'LOW',
      priorityLevel: 'P4',
      trend: 'STABLE',
      trendPct: 0.0,
      componentScores: { rainfall: 0.19, slope: 0.42, soil: 0.25, landCover: 0.20, drainage: 0.22, historical: 0.26 },
      inputs: {
        rainfall_current_mmph: 1.2,
        rainfall_24h_mm: 11.0,
        rainfall_72h_mm: 28.0,
        forecast_6h_mm: 2.0,
        forecast_24h_mm: 8.0,
        slope_deg: 24.5,
        soilSusceptibility: 0.35,
        landCoverSusceptibility: 0.22,
        drainageProximityKm: 1.4,
        historicalEventsNearby: 0,
      },
      explanation: [{ factor: 'Low Valley Relief', value: 'Normal', contribution: 65, label: 'LOW' }],
      recommendations: ['Normal routine operations'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'boko',
    name: 'Boko Foothills Catchment',
    district: 'Kamrup Rural',
    state: 'Assam',
    country: 'India',
    coordinates: { lat: 25.9833, lon: 91.2333 },
    population: 48000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-boko',
      locationId: 'boko',
      locationName: 'Boko Foothills Catchment',
      district: 'Kamrup Rural',
      state: 'Assam',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 18.5,
      impactScore: 15.0,
      finalScore: 17.0,
      riskLevel: 'LOW',
      priorityLevel: 'P4',
      trend: 'STABLE',
      trendPct: 0.0,
      componentScores: { rainfall: 0.14, slope: 0.28, soil: 0.18, landCover: 0.16, drainage: 0.15, historical: 0.22 },
      inputs: {
        rainfall_current_mmph: 0.4,
        rainfall_24h_mm: 6.0,
        rainfall_72h_mm: 16.0,
        forecast_6h_mm: 1.0,
        forecast_24h_mm: 4.0,
        slope_deg: 18.2,
        soilSusceptibility: 0.28,
        landCoverSusceptibility: 0.18,
        drainageProximityKm: 1.8,
        historicalEventsNearby: 0,
      },
      explanation: [{ factor: 'Stable Terrain Base', value: 'Normal', contribution: 70, label: 'LOW' }],
      recommendations: ['Normal routine operations'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'hajo',
    name: 'Hajo Hillocks',
    district: 'Kamrup Rural',
    state: 'Assam',
    country: 'India',
    coordinates: { lat: 26.2483, lon: 91.5278 },
    population: 29000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-hajo',
      locationId: 'hajo',
      locationName: 'Hajo Hillocks',
      district: 'Kamrup Rural',
      state: 'Assam',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 15.0,
      impactScore: 12.0,
      finalScore: 13.8,
      riskLevel: 'LOW',
      priorityLevel: 'P4',
      trend: 'STABLE',
      trendPct: 0.0,
      componentScores: { rainfall: 0.12, slope: 0.22, soil: 0.15, landCover: 0.14, drainage: 0.12, historical: 0.18 },
      inputs: {
        rainfall_current_mmph: 0.2,
        rainfall_24h_mm: 4.5,
        rainfall_72h_mm: 12.0,
        forecast_6h_mm: 1.0,
        forecast_24h_mm: 3.0,
        slope_deg: 15.0,
        soilSusceptibility: 0.24,
        landCoverSusceptibility: 0.15,
        drainageProximityKm: 2.0,
        historicalEventsNearby: 0,
      },
      explanation: [{ factor: 'Low Slope Elevation', value: 'Normal', contribution: 80, label: 'LOW' }],
      recommendations: ['Normal routine operations'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'lakhipur',
    name: 'Lakhipur Cachar Sector',
    district: 'Cachar',
    state: 'Assam',
    country: 'India',
    coordinates: { lat: 24.7944, lon: 93.0111 },
    population: 38000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-lakhipur',
      locationId: 'lakhipur',
      locationName: 'Lakhipur Cachar Sector',
      district: 'Cachar',
      state: 'Assam',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 16.2,
      impactScore: 14.0,
      finalScore: 15.2,
      riskLevel: 'LOW',
      priorityLevel: 'P4',
      trend: 'STABLE',
      trendPct: 0.0,
      componentScores: { rainfall: 0.16, slope: 0.20, soil: 0.18, landCover: 0.15, drainage: 0.14, historical: 0.20 },
      inputs: {
        rainfall_current_mmph: 0.6,
        rainfall_24h_mm: 8.0,
        rainfall_72h_mm: 20.0,
        forecast_6h_mm: 1.0,
        forecast_24h_mm: 5.0,
        slope_deg: 14.0,
        soilSusceptibility: 0.31,
        landCoverSusceptibility: 0.19,
        drainageProximityKm: 1.6,
        historicalEventsNearby: 0,
      },
      explanation: [{ factor: 'Barak Valley Alluvial Plain', value: 'Normal', contribution: 75, label: 'LOW' }],
      recommendations: ['Normal routine operations'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'krishnai',
    name: 'Krishnai River Catchment',
    district: 'Goalpara',
    state: 'Assam',
    country: 'India',
    coordinates: { lat: 25.9667, lon: 90.6833 },
    population: 21000,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-krishnai',
      locationId: 'krishnai',
      locationName: 'Krishnai River Catchment',
      district: 'Goalpara',
      state: 'Assam',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 17.8,
      impactScore: 13.5,
      finalScore: 16.0,
      riskLevel: 'LOW',
      priorityLevel: 'P4',
      trend: 'STABLE',
      trendPct: 0.0,
      componentScores: { rainfall: 0.15, slope: 0.24, soil: 0.17, landCover: 0.15, drainage: 0.16, historical: 0.19 },
      inputs: {
        rainfall_current_mmph: 0.5,
        rainfall_24h_mm: 7.2,
        rainfall_72h_mm: 18.0,
        forecast_6h_mm: 1.0,
        forecast_24h_mm: 4.0,
        slope_deg: 16.5,
        soilSusceptibility: 0.29,
        landCoverSusceptibility: 0.17,
        drainageProximityKm: 1.5,
        historicalEventsNearby: 0,
      },
      explanation: [{ factor: 'Garo Hills Foothill Plain', value: 'Normal', contribution: 72, label: 'LOW' }],
      recommendations: ['Normal routine operations'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
  {
    id: 'mynso',
    name: 'Mynso Jaintia Escarpment',
    district: 'West Jaintia Hills',
    state: 'Meghalaya',
    country: 'India',
    coordinates: { lat: 25.5333, lon: 92.3167 },
    population: 9200,
    isActive: true,
    addedAt: '2026-01-15T00:00:00Z',
    latestRisk: {
      id: 'risk-mynso',
      locationId: 'mynso',
      locationName: 'Mynso Jaintia Escarpment',
      district: 'West Jaintia Hills',
      state: 'Meghalaya',
      timestamp: new Date().toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: 33.4,
      impactScore: 28.0,
      finalScore: 31.2,
      riskLevel: 'MODERATE',
      priorityLevel: 'P3',
      trend: 'STABLE',
      trendPct: 0.0,
      componentScores: { rainfall: 0.28, slope: 0.51, soil: 0.35, landCover: 0.29, drainage: 0.31, historical: 0.35 },
      inputs: {
        rainfall_current_mmph: 2.1,
        rainfall_24h_mm: 16.0,
        rainfall_72h_mm: 36.0,
        forecast_6h_mm: 3.0,
        forecast_24h_mm: 10.0,
        slope_deg: 27.5,
        soilSusceptibility: 0.44,
        landCoverSusceptibility: 0.32,
        drainageProximityKm: 0.90,
        historicalEventsNearby: 0,
      },
      explanation: [{ factor: 'Valley Infiltration', value: 'Normal', contribution: 55, label: 'LOW' }],
      recommendations: ['Normal routine operations'],
      dataQuality: { rainfall: 'GOOD' },
      isDemo: false,
    },
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alt-aizawl-1',
    locationId: 'aizawl',
    locationName: 'Aizawl Catchment',
    district: 'Aizawl',
    state: 'Mizoram',
    riskScore: 75.8,
    riskLevel: 'CRITICAL',
    triggerThreshold: 70.0,
    priorityLevel: 'P1',
    reason: 'CRITICAL HAZARD: Slope Saturation Threshold Breached (86.5mm/24h) on Ramhlun South ridge slope (>35°). Evacuation protocol active.',
    explanation: [
      { factor: 'Rainfall 24h', value: '86.5 mm', contribution: 38, label: 'HIGH' },
      { factor: 'Slope Gradient', value: '38.4°', contribution: 32, label: 'HIGH' },
      { factor: 'Soil Saturation', value: '84%', contribution: 30, label: 'HIGH' },
    ],
    status: 'NEW',
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    source: 'RULE_ENGINE_NER',
    isDemo: false,
  },
  {
    id: 'alt-gangtok-1',
    locationId: 'gangtok',
    locationName: 'Gangtok Urban Ridge',
    district: 'East Sikkim',
    state: 'Sikkim',
    riskScore: 70.1,
    riskLevel: 'CRITICAL',
    triggerThreshold: 70.0,
    priorityLevel: 'P1',
    reason: 'CRITICAL HAZARD: Active Ground Creep Detected near Deorali slope after 72.8mm rainfall surge.',
    explanation: [
      { factor: 'Soil Moisture', value: '81%', contribution: 42, label: 'HIGH' },
      { factor: 'Slope Incline', value: '36.8°', contribution: 33, label: 'HIGH' },
    ],
    status: 'NEW',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    source: 'RULE_ENGINE_NER',
    isDemo: false,
  },
  {
    id: 'alt-shillong-1',
    locationId: 'shillong',
    locationName: 'Shillong Peak & Valley',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    riskScore: 67.1,
    riskLevel: 'HIGH',
    triggerThreshold: 55.0,
    priorityLevel: 'P2',
    reason: 'HIGH HAZARD: 64.2mm precipitation has induced heavy drainage runoff along NH-6 highway hill cuts.',
    explanation: [
      { factor: 'NH-6 Highway Proximity', value: '60m', contribution: 40, label: 'HIGH' },
      { factor: '72h Antecedent Rain', value: '118.4 mm', contribution: 35, label: 'HIGH' },
    ],
    status: 'ACKNOWLEDGED',
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    source: 'RULE_ENGINE_NER',
    isDemo: false,
  },
  {
    id: 'alt-durtlang-1',
    locationId: 'durtlang',
    locationName: 'Durtlang North Ridge',
    district: 'Aizawl',
    state: 'Mizoram',
    riskScore: 63.8,
    riskLevel: 'HIGH',
    triggerThreshold: 55.0,
    priorityLevel: 'P2',
    reason: 'HIGH HAZARD: Heavy rain causing wedge failure risk along Durtlang Leitan cliff sector.',
    explanation: [
      { factor: 'Slope Gradient', value: '37.5°', contribution: 55, label: 'HIGH' },
    ],
    status: 'INVESTIGATING',
    createdAt: new Date(Date.now() - 140 * 60000).toISOString(),
    source: 'RULE_ENGINE_NER',
    isDemo: false,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'authority',
    type: 'ALERT',
    channel: 'IN_APP',
    title: 'P1 Critical Alert Triggered for Aizawl',
    body: 'Aizawl risk score escalated to 75.8/100 (CRITICAL). Automated CAP broadcast prepared.',
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    isRead: false,
    deliveryStatus: 'DELIVERED',
    relatedLocationId: 'aizawl',
  },
  {
    id: 'notif-2',
    userId: 'authority',
    type: 'ALERT',
    channel: 'IN_APP',
    title: 'P1 Critical Alert Triggered for Gangtok',
    body: 'Gangtok risk score escalated to 70.1/100 (CRITICAL). Deorali sector warning active.',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    isRead: false,
    deliveryStatus: 'DELIVERED',
    relatedLocationId: 'gangtok',
  },
  {
    id: 'notif-3',
    userId: 'authority',
    type: 'SYSTEM',
    channel: 'IN_APP',
    title: 'NDMA SitRep Auto-Generated',
    body: 'Official NER Regional Disaster Situation Report (SitRep-NER-2026) is ready for export.',
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
    isRead: true,
    deliveryStatus: 'DELIVERED',
  },
];

export const MOCK_HISTORICAL_LANDSLIDES: HistoricalLandslide[] = [
  {
    id: 'hist-ls-1',
    date: '2024-05-28',
    coordinates: { lat: 23.7450, lon: 92.7210 },
    locationName: 'Melthum & Hlimen Stone Quarry Landslide Disaster',
    district: 'Aizawl',
    state: 'Mizoram',
    source: 'GSI_HISTORICAL_CATALOG / NDMA_INCIDENT_REPORT',
    trigger: 'Cyclone Remal extreme cloudburst (210.5 mm/24h) coupled with unscientific vertical quarry cuts',
    fatalities: 29,
    injuries: 18,
    missing: 4,
    displaced: 160,
    description: 'Catastrophic slope collapse at an active stone quarry and adjacent settlement during Cyclone Remal, destroying 42 residential homes and burying workers in Melthum, Hlimen, and Salem Veng.',
    whyItHappened: 'Severe antecedent rainfall saturation (210.5mm in 24 hours) raised pore-water pressure to critical levels along the dipping bedding planes of Surma Group sandstone and siltstone. Saturated colluvium lost all frictional shear resistance on a 38° slope, triggering a massive 450,000 m³ planar debris avalanche.',
    whatWentWrong: '1) Zero automated threshold-based early warning alerts were broadcasted to downhill quarry workers. 2) Illegal vertical quarry excavation without geotechnical benching or retaining berms had severely undercut the slope toe. 3) Informal worker settlements were permitted directly in the active debris runout cone.',
    precautionsGovtCouldHaveTaken: '1) Issue mandatory pre-emptive evacuation orders 12 hours prior based on IMD Cyclone Remal tracking. 2) Deploy geofenced emergency SMS alerts to mobile phones within a 2km radius of steep quarry zones. 3) Enforce strict slope stabilization bylaws prohibiting residential quarters within 200m of quarry slopes.',
    infrastructureImpact: '42 residential buildings destroyed, National Highway 54 (Aizawl–Silchar lifeline) blocked for 6 days, high-tension power grid severed.',
    lessonsLearned: 'Mandatory geotechnical stability audits for all stone quarries; automated rain-gauge telemetry integration with district emergency operations center.',
    nearbyLocations: [{ locationId: 'aizawl', distanceKm: 1.4 }],
    qualityFlag: 'GOOD',
  },
  {
    id: 'hist-ls-2',
    date: '2023-10-04',
    coordinates: { lat: 27.3250, lon: 88.6100 },
    locationName: 'Teesta Basin GLOF & Chungthang-Dikchu Slope Collapses',
    district: 'East Sikkim',
    state: 'Sikkim',
    source: 'GSI_HISTORICAL_CATALOG / SIKKIM_SDMA',
    trigger: 'South Lhonak Glacial Lake Outburst Flood (GLOF) surge combined with heavy cloudburst run-off',
    fatalities: 42,
    injuries: 76,
    missing: 77,
    displaced: 2400,
    description: 'Catastrophic moraine dam breach at South Lhonak lake triggered a 20-meter flood surge that scoured river banks and initiated cascading multi-slope translational landslides throughout the Teesta River basin.',
    whyItHappened: 'Moraine collapse released ~65 million m³ of glacial meltwater down the narrow Teesta gorge at 50 km/h. Violent bank toe-erosion destabilized colluvial overburden and weathered gneiss bedrock slopes along Chungthang, Dikchu, and Singtam, causing over 30 simultaneous mega-landslides.',
    whatWentWrong: '1) Downstream early warning sirens failed to activate automatically when glacial lake sensors detected lake-level collapse. 2) Optical fiber communication cables along the river highway snapped immediately, causing a total blackout. 3) Traffic on NH-10 was not halted early enough to prevent vehicle entrapment.',
    precautionsGovtCouldHaveTaken: '1) Satellite radar telemetry with automatic threshold triggers to blast emergency radio and cell broadcast alerts to all downstream villages within 5 minutes of lake breach. 2) Redundant satellite-based communication links for emergency control rooms. 3) Immediate automated highway barrier closure on NH-10 at Melli and Rangpo checkpoints.',
    infrastructureImpact: 'Chungthang Hydroelectric Dam washed away, 14 major bridges destroyed, NH-10 connectivity to mainland India severed for over 3 weeks.',
    lessonsLearned: 'Installation of automated downstream acoustic siren networks; rigorous moraine-lowering engineering on high-risk Himalayan glacial lakes.',
    nearbyLocations: [{ locationId: 'gangtok', distanceKm: 2.1 }],
    qualityFlag: 'GOOD',
  },
  {
    id: 'hist-ls-3',
    date: '2022-06-30',
    coordinates: { lat: 24.8100, lon: 93.6200 },
    locationName: 'Tupul Railway Camp Mega Landslide Disaster',
    district: 'Noney & Senapati',
    state: 'Manipur',
    source: 'GSI_HISTORICAL_CATALOG / NDRF_MISSION_RECORD',
    trigger: 'Relentless 5-day continuous monsoon rainfall (340mm) triggering planar debris avalanche on deforested cut slope',
    fatalities: 58,
    injuries: 18,
    missing: 3,
    displaced: 350,
    description: 'Massive slope collapse buried the 107 Territorial Army camp and railway construction workers at Tupul station, damming the Ijei river and creating a secondary hazardous artificial reservoir.',
    whyItHappened: 'Extensive excavation for the Jiribam–Imphal railway alignment had steepened the slope to >40° without adequate drainage benches. 5 days of relentless monsoon rain liquefied loose weathered Disang shale and colluvium, causing over 1.2 million m³ of debris to slide down the mountain within 45 seconds.',
    whatWentWrong: '1) The temporary military and worker camp was sited directly inside an active alluvial debris runout channel. 2) Heavy earth-moving machinery had altered the natural hillside drainage pathways. 3) No real-time slope movement sensors (inclinometers/piezometers) were deployed on the excavation site.',
    precautionsGovtCouldHaveTaken: '1) Geotechnical hazard zonation mapping prior to camp establishment—prohibiting any temporary or permanent structures in historical runout zones. 2) 24/7 slope displacement monitoring using automated robotic total stations and acoustic emission sensors. 3) Pre-emptive relocation of personnel during heavy rainfall warnings.',
    infrastructureImpact: 'Railway yard completely demolished, Ijei River dammed creating a 15-meter deep artificial lake threatening downstream villages, rescue operations took 21 days.',
    lessonsLearned: 'Zero-tolerance policy for worker camps in alluvial fan corridors; mandatory sub-surface horizontal drainage drilling along all railway cut slopes.',
    nearbyLocations: [{ locationId: 'senapati', distanceKm: 18.0 }],
    qualityFlag: 'GOOD',
  },
  {
    id: 'hist-ls-4',
    date: '2022-05-15',
    coordinates: { lat: 25.1764, lon: 93.0182 },
    locationName: 'Haflong & Jatinga Multi-Site Hill Railway Disaster',
    district: 'Dima Hasao',
    state: 'Assam',
    source: 'GSI_HISTORICAL_CATALOG / NF_RAILWAY_REPORT',
    trigger: 'Extreme pre-monsoon cloudburst (385mm in 72 hours) triggering 54 concurrent slope failures',
    fatalities: 14,
    injuries: 32,
    missing: 2,
    displaced: 850,
    description: 'Multiple landslides and mudflows completely buried the Lumding–Badarpur mountain railway corridor, inundating New Haflong Railway Station and stranding passenger trains in deep canyons.',
    whyItHappened: 'Deep weathered shale-sandstone overburden saturated by 385mm of rain lost shear strength on 32° slopes. Hill cutting for railway double-tracking and highway expansion without adequate retaining walls caused progressive retrogressive failures across 54 separate locations.',
    whatWentWrong: '1) Passenger trains were dispatched into the hill section despite red rainfall warnings issued by IMD. 2) Drainage culverts along the tracks were clogged with forest debris and construction silt. 3) Lack of real-time debris flow detection sensors along track cuttings.',
    precautionsGovtCouldHaveTaken: '1) Automatic suspension of passenger rail traffic once 24h rainfall exceeded the 100mm threshold. 2) Deployment of automated optical rain-gauges linked directly to railway signal interlocking systems. 3) Regular pre-monsoon clearing and widening of hill culverts.',
    infrastructureImpact: 'New Haflong railway station submerged under 4 meters of mud, railway tracks suspended in mid-air over chasms, entire Barak Valley cut off from rail access for 2 months.',
    lessonsLearned: 'Integration of real-time early warning telemetry with railway operations; construction of reinforced rock-sheds in high-vulnerability canyon cuttings.',
    nearbyLocations: [{ locationId: 'haflong', distanceKm: 0.8 }],
    qualityFlag: 'GOOD',
  },
  {
    id: 'hist-ls-5',
    date: '2024-06-18',
    coordinates: { lat: 25.5920, lon: 91.8810 },
    locationName: 'Mawlai Bypass & Pynursla Highway Slope Failure',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    source: 'GSI_HISTORICAL_CATALOG / MEGHALAYA_PWD',
    trigger: 'Colluvial soil liquefaction over quartzite bedrock following 185mm cloudburst downpour',
    fatalities: 6,
    injuries: 14,
    missing: 1,
    displaced: 120,
    description: 'Heavy rotational debris flow crashed down the Mawlai bypass slope, crushing 3 commercial vehicles and blocking National Highway 6 (the critical lifeline to Tripura and Mizoram).',
    whyItHappened: 'Continuous torrential rain over-saturated loose lateritic topsoil overlying impervious quartzite bedrock. Water pooled behind unmaintained roadside retaining walls, causing hydrostatic pressure buildup until the wall gave way.',
    whatWentWrong: '1) Weep holes in roadside retaining walls were blocked with calcified sediment and weeds, preventing drainage. 2) No dynamic warning signs or digital variable message boards were present to warn oncoming night traffic.',
    precautionsGovtCouldHaveTaken: '1) Mandatory pre-monsoon unclogging of weep holes and installation of sub-horizontal drain pipes. 2) Automated rainfall-triggered traffic barrier deployment to divert heavy vehicles during cloudbursts. 3) Geo-grid slope reinforcement on steep cut faces.',
    infrastructureImpact: 'NH-6 arterial corridor blocked for 48 hours, over 600 trucks stranded, estimated trade loss of ₹18 Crores.',
    lessonsLearned: 'Routine maintenance protocols for highway drainage; application of bio-engineering vetiver grass slopes.',
    nearbyLocations: [{ locationId: 'shillong', distanceKm: 3.2 }],
    qualityFlag: 'GOOD',
  },
  {
    id: 'hist-ls-6',
    date: '2023-08-12',
    coordinates: { lat: 25.6200, lon: 94.1150 },
    locationName: 'Phesama & Viswema NH-29 Sinking Zone Subsidence',
    district: 'Kohima',
    state: 'Nagaland',
    source: 'GSI_HISTORICAL_CATALOG / NAGALAND_SDMA',
    trigger: 'Progressive creeping landslide triggered by Disang shale plastic deformation and toe erosion',
    fatalities: 3,
    injuries: 9,
    missing: 0,
    displaced: 210,
    description: 'Slow-moving rotational slump mobilized into rapid earth flow during peak August monsoon, sinking a 300-meter stretch of NH-29 and destabilizing 18 hillside residences in Phesama village.',
    whyItHappened: 'Disang shale formations are rich in smectite clay, which swells and loses up to 80% of its cohesion when wet. Groundwater seepage from uphill terraced paddy cultivation lubricated the shear plane on a 28° slope.',
    whatWentWrong: '1) Unregulated uncontrolled agricultural water discharge from uphill fields directly into the sinking slope. 2) Continued heavy multi-axle freight traffic overloaded the structurally weakened road pavement.',
    precautionsGovtCouldHaveTaken: '1) Construct lined catch-water drains uphill to divert surface runoff away from the vulnerable slide mass. 2) Impose weight restrictions on heavy commercial vehicles during continuous monsoon weeks. 3) Provide early subsidies for micro-piling slope stabilization.',
    infrastructureImpact: 'NH-29 lifeline severed between Kohima and Manipur border for 10 days, 18 homes declared structurally unsafe and evacuated.',
    lessonsLearned: 'Agricultural water management integrated with slope stability; real-time satellite InSAR monitoring for creeping subsidence zones.',
    nearbyLocations: [{ locationId: 'kohima', distanceKm: 4.5 }],
    qualityFlag: 'GOOD',
  },
];

export function getMockLocationDetails(id: string): LocationDetail {
  const loc = MOCK_LOCATIONS.find((l) => l.id.toLowerCase() === id.toLowerCase()) || MOCK_LOCATIONS[0];
  const risk = loc.latestRisk || MOCK_LOCATIONS[0].latestRisk!;

  return {
    location: loc,
    terrain: {
      locationId: loc.id,
      elevation_m: 1132,
      avgSlope_deg: risk.inputs.slope_deg,
      maxSlope_deg: risk.inputs.slope_deg + 8.5,
      slopeSusceptibility: 0.82,
      dem_source: 'SRTM_30M_GLOBAL_DEM',
      processedAt: new Date().toISOString(),
      qualityFlag: 'GOOD',
    },
    soil: {
      locationId: loc.id,
      soilType: 'Clay Loam (Typic Dystrochrepts)',
      clay_pct: 38,
      sand_pct: 28,
      silt_pct: 34,
      bulkDensity: 1.35,
      organicCarbon: 1.8,
      waterRetentionIndex: 0.74,
      soilSusceptibility: risk.inputs.soilSusceptibility,
      source: 'ICAR_NBSS_LUP',
      fetchedAt: new Date().toISOString(),
      qualityFlag: 'GOOD',
    },
    landCover: {
      locationId: loc.id,
      dominantClass: 'Mixed Dense Hill Vegetation & Built-Up Ridge',
      classification: { Forest: 58, Urban: 26, Agriculture: 12, Water: 4 },
      source: 'ESA_WORLDCOVER_10M',
      year: 2025,
      landCoverSusceptibility: risk.inputs.landCoverSusceptibility,
      qualityFlag: 'GOOD',
    },
    drainage: {
      locationId: loc.id,
      nearestRiver: { name: 'Chite Lui River', distanceKm: 0.45 },
      nearestStream: { distanceKm: 0.15 },
      drainageDensity: 3.4,
      source: 'HYDROSHEDS_NER',
      qualityFlag: 'GOOD',
    },
    infrastructure: {
      locationId: loc.id,
      roads: Array.from({ length: 18 }, (_, i) => ({ osmId: `osm-rd-${i + 1}`, type: 'primary', distanceKm: 0.05 + i * 0.1 })),
      bridges: Array.from({ length: 4 }, (_, i) => ({ osmId: `osm-br-${i + 1}`, name: `Bridge #${i + 1}`, distanceKm: 0.2 + i * 0.3 })),
      schools: Array.from({ length: 14 }, (_, i) => ({ osmId: `osm-sc-${i + 1}`, name: `Govt School #${i + 1}`, distanceKm: 0.3 + i * 0.15 })),
      hospitals: Array.from({ length: 6 }, (_, i) => ({ osmId: `osm-hp-${i + 1}`, name: `Health Centre #${i + 1}`, distanceKm: 0.15 + i * 0.2 })),
      settlements: Array.from({ length: 12 }, (_, i) => ({ name: `Ward #${i + 1}`, population: 15000, distanceKm: 0.1 + i * 0.2 })),
      source: 'OPENSTREETMAP_OVERPASS_API',
      fetchedAt: new Date().toISOString(),
      qualityFlag: 'GOOD',
    },
    forecast: {
      locationId: loc.id,
      generatedAt: new Date().toISOString(),
      source: 'IMD_WRF_NUMERICAL_MODEL',
      hourly: Array.from({ length: 24 }, (_, i) => ({
        hour: i + 1,
        precipitation_mm: Math.round((Math.sin(i / 3) * 6 + 8) * 10) / 10,
        probability: Math.min(95, Math.round((60 + Math.sin(i / 4) * 30))),
      })),
      next6h_mm: risk.inputs.forecast_6h_mm,
      next24h_mm: risk.inputs.forecast_24h_mm,
      next72h_mm: risk.inputs.forecast_24h_mm * 2.2,
      qualityFlag: 'GOOD',
    },
    latestRainfall: {
      id: `rain-${loc.id}`,
      locationId: loc.id,
      timestamp: new Date().toISOString(),
      current_mmph: risk.inputs.rainfall_current_mmph,
      intensity: risk.inputs.rainfall_current_mmph > 15 ? 'heavy' : risk.inputs.rainfall_current_mmph > 5 ? 'moderate' : 'light',
      cumulative_24h_mm: risk.inputs.rainfall_24h_mm,
      cumulative_72h_mm: risk.inputs.rainfall_72h_mm,
      source: 'IMD_AWS_TELEMETRY',
      qualityFlag: 'GOOD',
      ingestedAt: new Date().toISOString(),
    },
    riskHistory: Array.from({ length: 14 }, (_, i) => ({
      id: `risk-hist-${i}`,
      locationId: loc.id,
      locationName: loc.name,
      district: loc.district,
      state: loc.state,
      timestamp: new Date(Date.now() - (13 - i) * 86400000).toISOString(),
      modelVersion: 'v2.4-hybrid-ner',
      hazardScore: Math.min(100, Math.max(15, Math.round((risk.hazardScore - (13 - i) * 2.5) * 10) / 10)),
      impactScore: risk.impactScore,
      finalScore: Math.min(100, Math.max(15, Math.round((risk.finalScore - (13 - i) * 2.5) * 10) / 10)),
      riskLevel: (risk.finalScore - (13 - i) * 2.5) >= 70 ? 'CRITICAL' : (risk.finalScore - (13 - i) * 2.5) >= 55 ? 'HIGH' : 'MODERATE',
      priorityLevel: (risk.finalScore - (13 - i) * 2.5) >= 70 ? 'P1' : (risk.finalScore - (13 - i) * 2.5) >= 55 ? 'P2' : 'P3',
      trend: 'RISING',
      trendPct: 12.0,
      componentScores: risk.componentScores,
      inputs: risk.inputs,
      explanation: risk.explanation,
      recommendations: risk.recommendations,
      dataQuality: risk.dataQuality,
      isDemo: false,
    })),
    latestRisk: risk,
    nearbyLandslides: MOCK_HISTORICAL_LANDSLIDES.filter((ls) => ls.district === loc.district || ls.state === loc.state),
    alerts: MOCK_ALERTS.filter((a) => a.locationId === loc.id),
  };
}

export const MOCK_DATA_SOURCES: DataSource[] = [
  {
    id: 'src-imd-aws',
    name: 'IMD Automatic Weather Stations (AWS)',
    type: 'METEOROLOGICAL_TELEMETRY',
    url: 'https://mausam.imd.gov.in',
    updateFrequency: 'Every 15 Minutes',
    lastSuccessAt: new Date(Date.now() - 4 * 60000).toISOString(),
    lastAttemptAt: new Date(Date.now() - 4 * 60000).toISOString(),
    status: 'LIVE',
    coverage: 'Northeast India (NER) 20 Telemetry Towers',
    qualityNotes: 'Real-time rainfall rates (mm/h), 24h cumulative totals, and 72h antecedent soil moisture curves with 99.8% uptime.',
    recordCount: 14280,
    lastLatencyMs: 85,
    latestObservationTime: new Date(Date.now() - 4 * 60000).toISOString(),
  },
  {
    id: 'src-open-meteo',
    name: 'Open-Meteo High-Res NWP Doppler Radar',
    type: 'NUMERICAL_WEATHER_PREDICTION',
    url: 'https://api.open-meteo.com',
    updateFrequency: 'Hourly Cycle',
    lastSuccessAt: new Date(Date.now() - 18 * 60000).toISOString(),
    lastAttemptAt: new Date(Date.now() - 18 * 60000).toISOString(),
    status: 'LIVE',
    coverage: 'Eastern Himalayas & Barak/Surma Basin',
    qualityNotes: 'ECMWF & GFS multi-model blended hourly precipitation forecasts with 6h, 12h, and 24h short-term lookahead horizons.',
    recordCount: 2880,
    lastLatencyMs: 112,
    latestObservationTime: new Date(Date.now() - 18 * 60000).toISOString(),
  },
  {
    id: 'src-nasa-srtm',
    name: 'NASA SRTM 30m Global DEM',
    type: 'TOPOGRAPHIC_SURFACE_RASTER',
    url: 'https://cmr.earthdata.nasa.gov',
    updateFrequency: 'Static GIS Baseline',
    lastSuccessAt: new Date(Date.now() - 86400000).toISOString(),
    lastAttemptAt: new Date(Date.now() - 86400000).toISOString(),
    status: 'STATIC',
    coverage: 'Global 1-arc-second / 30m Resolution',
    qualityNotes: '30-meter spatial resolution Digital Elevation Model computing slope gradient, aspect, curvature, and Varnes classification.',
    recordCount: 24500,
    lastLatencyMs: 15,
    latestObservationTime: new Date().toISOString(),
  },
  {
    id: 'src-soilgrids',
    name: 'ISRIC SoilGrids v2.0 / ICAR-NBSS&LUP',
    type: 'GEOTECHNICAL_PEDOLOGY',
    url: 'https://rest.isric.org',
    updateFrequency: 'Quarterly Calibration',
    lastSuccessAt: new Date(Date.now() - 86400000).toISOString(),
    lastAttemptAt: new Date(Date.now() - 86400000).toISOString(),
    status: 'STATIC',
    coverage: 'Northeast States (6 Geotechnical Layers)',
    qualityNotes: 'Clay/Sand/Silt fractions (0-200cm), soil water retention index, bulk density, and geotechnical susceptibility factor.',
    recordCount: 8400,
    lastLatencyMs: 24,
    latestObservationTime: new Date().toISOString(),
  },
  {
    id: 'src-worldcover',
    name: 'ESA WorldCover 10m Sentinel-2 Classification',
    type: 'SATELLITE_REMOTE_SENSING',
    url: 'https://esa-worldcover.org',
    updateFrequency: 'Annual Sentinel-2 Cycle',
    lastSuccessAt: new Date(Date.now() - 86400000).toISOString(),
    lastAttemptAt: new Date(Date.now() - 86400000).toISOString(),
    status: 'STATIC',
    coverage: '10m Land Cover / Land Use (LULC)',
    qualityNotes: 'Multi-spectral satellite mapping of hillside tree cover, shrubland, steep barren escarpments, and urban settlements.',
    recordCount: 16200,
    lastLatencyMs: 18,
    latestObservationTime: new Date().toISOString(),
  },
  {
    id: 'src-osm-overpass',
    name: 'OpenStreetMap (OSM) Overpass Infrastructure API',
    type: 'CRITICAL_INFRASTRUCTURE',
    url: 'https://overpass-api.de',
    updateFrequency: 'Daily Vector Sync',
    lastSuccessAt: new Date(Date.now() - 42 * 60000).toISOString(),
    lastAttemptAt: new Date(Date.now() - 42 * 60000).toISOString(),
    status: 'LIVE',
    coverage: '5km Buffer Zones around 20 Catchments',
    qualityNotes: 'Live asset extraction: 372 Roads & Highways, 93 Bridges, 382 Schools/Colleges, and 92 Hospitals & Health Centres.',
    recordCount: 939,
    lastLatencyMs: 145,
    latestObservationTime: new Date(Date.now() - 42 * 60000).toISOString(),
  },
  {
    id: 'src-fast2sms',
    name: 'Fast2SMS Enterprise Cloud Gateway (NDMA DLT)',
    type: 'EMERGENCY_DISPATCH_SMS',
    url: 'https://www.fast2sms.com',
    updateFrequency: 'Event-Driven Trigger',
    lastSuccessAt: new Date(Date.now() - 5 * 60000).toISOString(),
    lastAttemptAt: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'LIVE',
    coverage: 'Pan-India GSM Cellular Telephony',
    qualityNotes: 'TRAI DLT-registered emergency dispatch delivering automated siren SMS warnings to field responders within <5 seconds.',
    recordCount: 142,
    lastLatencyMs: 210,
    latestObservationTime: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'src-hydrosheds',
    name: 'HydroSHEDS Hydrography & River Corridors',
    type: 'HYDROLOGICAL_VECTOR',
    url: 'https://www.hydrosheds.org',
    updateFrequency: 'Hydrological Baseline',
    lastSuccessAt: new Date(Date.now() - 86400000).toISOString(),
    lastAttemptAt: new Date(Date.now() - 86400000).toISOString(),
    status: 'STATIC',
    coverage: 'Brahmaputra & Barak River Headwaters',
    qualityNotes: 'Flow accumulation, drainage density, and stream proximity buffers for slope wash and channelized debris flows.',
    recordCount: 1420,
    lastLatencyMs: 30,
    latestObservationTime: new Date().toISOString(),
  },
];

